### Content

1. [Declare Variables](./01. Declare Variables)
1. [Float or Double](./02. Float or Double)
1. [Variable in Hexadecimal Format](./03. Variable in Hexadecimal Format)
1. [Unicode Character](./04. Unicode Character)
1. [Boolean Variable](./05. Boolean Variable)
1. [Strings and Objects](./06. Strings and Objects)
1. [Quotes in Strings](./07. Quotes in Strings)
1. [Isosceles Triangle](./08. Isosceles Triangle)
1. [Exchange Variable Values](./09. Exchange Variable Values)
1. [Employee Data](./10. Employee Data)
1. [Bank Account Data](./11. Bank Account Data)
1. [Null Values Arithmetic](./12. Null Values Arithmetic)
1. [Comparing Floats](./13. Comparing Floats)
1. [Print the ASCII Table](./14. Print the ASCII Table)
